[package]
name = "tourney-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = {version = "0.6.3", features = ["serde-1"]}
serde = {version = "1.0.164",  features = ["derive"]}
serde_json = "1.0.96"
